import React, { ReactNode } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@app/styles/globals.css";
import { MainLayout } from '@repo/core/components';
import { getServerSiteContext, setRequestLocale } from '@repo/core/server';
import { DefaultLayoutProps } from '@repo/core';
import { SiteContextProvider } from '@repo/core/client';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface RootLayoutProps extends DefaultLayoutProps {
  children: any;
  params: {
    baseSite: string;
    locale: string;
    currency: string;
  };
}
export default async function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  await setRequestLocale(locale);
  const siteContext = await getServerSiteContext();


  return (
    <html lang={locale || siteContext.language}>
      <body className={inter.className}>
        <SiteContextProvider siteContext={siteContext}>
          <MainLayout siteContext={siteContext}>
            {children}
          </MainLayout>
        </SiteContextProvider>
      </body>
    </html>
  );
}
