import React, { Suspense } from 'react';
import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import { type DefaultLayoutProps } from '@commercetools-next/core';
import { MainLayout } from '@commercetools-next/core/components';
import "@app/styles/globals.css";

const font = Red_Hat_Display({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface RootLayoutProps extends DefaultLayoutProps {
  params: {
    baseSite: string;
    locale: string;
    currency: string;
  };
}
export default async function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  return (
    <html lang={locale}>
      <body className={font.className}>
      <Suspense>
      <MainLayout>{children}</MainLayout>
      </Suspense>
    </body>
    </html>
  );
}
